services:
  traefik:
    image: traefik:3.3
    environment:
      TRAEFIK_DASHBOARD_HOST: ${TRAEFIK_DASHBOARD_HOST}
      TRAEFIK_DASHBOARD_BASICAUTH_USERNAME: ${TRAEFIK_DASHBOARD_BASICAUTH_USERNAME}
      TRAEFIK_DASHBOARD_BASICAUTH_PASSWORD: ${TRAEFIK_DASHBOARD_BASICAUTH_PASSWORD}
      TRAEFIK_CR_LE_ACME_EMAIL: ${TRAEFIK_CR_LE_ACME_EMAIL}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/traefik_dynamic.yml:/traefik_dynamic.yml:ro
      - ./traefik/acme.json:/acme.json
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp

  wg-easy:
    image: ghcr.io/santsukevich/amneziawg-easy:15
    restart: unless-stopped
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
      traefik:
    ports:
      - ${WG_PORT}:${WG_PORT}/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    labels:
      - traefik.enable=true
      - traefik.http.routers.wg-easy.rule=Host(`${WG_DASHBOARD_HOST}`)
      - traefik.http.routers.wg-easy.entrypoints=websecure
      - traefik.http.routers.wg-easy.service=wg-easy
      - traefik.http.services.wg-easy.loadbalancer.server.port=51821

volumes:
  etc_wireguard:

networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
  traefik:
